version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api_simulation:
    image: mysteriouscrawler/test
    container_name: api-simulation
    ports:
      - "3000:3000"
    environment:
      - PORT=3000

  app:
    image: michalrozga-crawler
    build: .
    env_file:
        - .env
    environment:
        API_URL: http://api_simulation:3000
        DATABASE_URL: postgres://${DB_USERNAME}:${DB_PASSWORD}@postgres-db:5432/${DB_NAME}
    ports:
        - "3001:3001"
    depends_on:
        - postgres
        - api_simulation

volumes:
  pgdata: