version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api_simulation:
    image: mysteriouscrawler/test
    container_name: api-simulation
    ports:
      - "3000:3000"
    environment:
      - PORT=3000

  app:
    image: node:14
    container_name: app
    command: npm run start
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - postgres
      - api_simulation
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app

volumes:
  pgdata: